apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: managedcluster
spec:
  package: docker.artifactory.k8s-it.internal.forterro.com/crossplane/managedcluster:v1.0
  # packagePullSecrets:
  #   - name: package-pull-secret
